#!/bin/bash

osascript <<EOD
	tell application "Spotify"
		set nOldSoundVolume to sound volume
		set sound volume to 0
		play
		repeat with nSoundVolume from sound volume to nOldSoundVolume by 1
			set sound volume to nSoundVolume
			delay 0.06
		end repeat
	end tell
EOD